name: flutter_logcat
description: "you can distribute check Log on Flutter's console. very simple usage!"
version: 1.0.5
homepage: https://donguran.com/pages/flutterlogcat
repository: https://github.com/b3lon9/flutter_logcat

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter